-- AGENDA v3.4 — tâches familiales + notifications Web Push
-- À exécuter UNE FOIS sur un projet déjà en v3.3.1.

begin;

alter table public.families
  add column if not exists timezone text not null default 'Europe/Paris';

alter table public.events
  add column if not exists reminder_minutes smallint default 60
  check (reminder_minutes is null or reminder_minutes between 0 and 10080);

create table if not exists public.tasks (
  id uuid primary key,
  family_id uuid not null references public.families(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 120),
  due_date date not null,
  due_time time,
  responsible_member_id uuid references public.members(id) on delete set null,
  priority text not null default 'normal' check (priority in ('low','normal','high')),
  status text not null default 'pending' check (status in ('pending','done')),
  notes text check (notes is null or char_length(notes) <= 300),
  reminder_minutes smallint default 60 check (reminder_minutes is null or reminder_minutes between 0 and 10080),
  completed_at timestamptz,
  completed_by uuid references auth.users(id) on delete set null,
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  updated_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tasks_family_due_idx on public.tasks (family_id, status, due_date, due_time);

create table if not exists public.notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  family_id uuid not null references public.families(id) on delete cascade,
  push_enabled boolean not null default false,
  event_reminders boolean not null default true,
  task_reminders boolean not null default true,
  daily_summary boolean not null default true,
  daily_summary_time time not null default '07:30',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  family_id uuid not null references public.families(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_idx on public.push_subscriptions (user_id, enabled);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  subscription_id uuid not null references public.push_subscriptions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  delivery_key text not null,
  kind text not null check (kind in ('event','task','summary')),
  sent_at timestamptz not null default now(),
  unique (subscription_id, delivery_key)
);

create or replace function public.validate_task_member()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.responsible_member_id is not null and not exists (
    select 1 from public.members m
    where m.id = new.responsible_member_id
      and m.family_id = new.family_id
  ) then
    raise exception 'Le responsable sélectionné n’appartient pas à cette famille.';
  end if;
  return new;
end;
$$;

-- Retourne uniquement les notifications arrivées à échéance et non encore envoyées.
-- Cette fonction n’est exécutable que par le rôle serveur de la fonction Edge.
create or replace function public.get_due_push_notifications(p_now timestamptz default now())
returns table (
  subscription_id uuid,
  user_id uuid,
  endpoint text,
  p256dh text,
  auth text,
  delivery_key text,
  kind text,
  title text,
  body text,
  url text,
  tag text
)
language sql
security definer
set search_path = public
as $$
with base as (
  select
    ps.id as subscription_id,
    ps.user_id,
    ps.endpoint,
    ps.p256dh,
    ps.auth,
    fu.family_id,
    f.name as family_name,
    f.symbol,
    f.timezone,
    f.quiet_mode,
    m.id as member_id,
    np.event_reminders,
    np.task_reminders,
    np.daily_summary,
    np.daily_summary_time
  from public.push_subscriptions ps
  join public.notification_preferences np
    on np.user_id = ps.user_id
   and np.family_id = ps.family_id
  join public.family_users fu
    on fu.user_id = ps.user_id
   and fu.family_id = ps.family_id
  join public.families f on f.id = fu.family_id
  left join public.members m
    on m.family_id = fu.family_id
   and m.linked_user_id = ps.user_id
  where ps.enabled = true
    and np.push_enabled = true
), event_candidates as (
  select
    b.subscription_id, b.user_id, b.endpoint, b.p256dh, b.auth,
    'event:' || e.id::text || ':' || coalesce(e.reminder_minutes::text, 'none') as delivery_key,
    'event'::text as kind,
    coalesce(b.symbol, '🌿') || ' ' || b.family_name as title,
    case
      when e.all_day then 'Aujourd’hui · ' || e.title
      when e.reminder_minutes = 1440 then 'Demain · ' || e.title
      when e.reminder_minutes = 60 then 'Dans 1 h · ' || e.title
      when e.reminder_minutes = 120 then 'Dans 2 h · ' || e.title
      when e.reminder_minutes = 0 then 'Maintenant · ' || e.title
      else 'Dans ' || e.reminder_minutes::text || ' min · ' || e.title
    end as body,
    './?event=' || e.id::text as url,
    'agenda-event-' || e.id::text as tag
  from base b
  join public.events e on e.family_id = b.family_id
  cross join lateral (
    select ((e.event_date + (case when e.all_day then time '09:00' else e.event_time end)) at time zone b.timezone)
      - make_interval(mins => e.reminder_minutes) as remind_at
  ) r
  where b.event_reminders = true
    and e.reminder_minutes is not null
    and (b.member_id is null or b.member_id = any(e.member_ids) or e.responsible_member_id = b.member_id)
    and p_now >= r.remind_at
    and p_now < r.remind_at + interval '5 minutes'
), task_candidates as (
  select
    b.subscription_id, b.user_id, b.endpoint, b.p256dh, b.auth,
    'task:' || t.id::text || ':' || coalesce(t.reminder_minutes::text, 'none') as delivery_key,
    'task'::text as kind,
    '✅ Tâche · ' || coalesce(b.symbol, '🌿') || ' ' || b.family_name as title,
    case
      when t.reminder_minutes = 1440 then 'À prévoir demain · ' || t.title
      when t.reminder_minutes = 60 then 'À faire dans 1 h · ' || t.title
      when t.reminder_minutes = 120 then 'À faire dans 2 h · ' || t.title
      when t.reminder_minutes = 0 then 'À faire maintenant · ' || t.title
      else 'À faire dans ' || t.reminder_minutes::text || ' min · ' || t.title
    end as body,
    './?task=' || t.id::text as url,
    'agenda-task-' || t.id::text as tag
  from base b
  join public.tasks t on t.family_id = b.family_id
  cross join lateral (
    select ((t.due_date + coalesce(t.due_time, time '09:00')) at time zone b.timezone)
      - make_interval(mins => t.reminder_minutes) as remind_at
  ) r
  where b.task_reminders = true
    and t.status = 'pending'
    and t.reminder_minutes is not null
    and (t.responsible_member_id is null or b.member_id is null or t.responsible_member_id = b.member_id)
    and p_now >= r.remind_at
    and p_now < r.remind_at + interval '5 minutes'
), summary_candidates as (
  select
    b.subscription_id, b.user_id, b.endpoint, b.p256dh, b.auth,
    'summary:' || b.user_id::text || ':' || ((p_now at time zone b.timezone)::date)::text as delivery_key,
    'summary'::text as kind,
    coalesce(b.symbol, '🌿') || ' Bonjour ' || b.family_name as title,
    (
      select count(*)::text || ' rendez-vous · '
      from public.events e
      where e.family_id = b.family_id
        and e.event_date = (p_now at time zone b.timezone)::date
        and (b.member_id is null or b.member_id = any(e.member_ids) or e.responsible_member_id = b.member_id)
    ) || (
      select count(*)::text || ' tâche(s) à suivre aujourd’hui'
      from public.tasks t
      where t.family_id = b.family_id
        and t.status = 'pending'
        and t.due_date <= (p_now at time zone b.timezone)::date
        and (t.responsible_member_id is null or b.member_id is null or t.responsible_member_id = b.member_id)
    ) as body,
    './'::text as url,
    'agenda-summary-' || ((p_now at time zone b.timezone)::date)::text as tag
  from base b
  cross join lateral (
    select (((p_now at time zone b.timezone)::date + b.daily_summary_time) at time zone b.timezone) as summary_at
  ) s
  where b.daily_summary = true
    and b.quiet_mode = false
    and p_now >= s.summary_at
    and p_now < s.summary_at + interval '5 minutes'
), candidates as (
  select * from event_candidates
  union all
  select * from task_candidates
  union all
  select * from summary_candidates
)
select c.*
from candidates c
where not exists (
  select 1
  from public.notification_deliveries d
  where d.subscription_id = c.subscription_id
    and d.delivery_key = c.delivery_key
)
order by c.kind, c.delivery_key
limit 250;
$$;

revoke all on function public.get_due_push_notifications(timestamptz) from public;
grant execute on function public.get_due_push_notifications(timestamptz) to service_role;

alter table public.tasks enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notification_deliveries enable row level security;

-- Tâches : toute la famille peut gérer les tâches de sa famille.
drop policy if exists tasks_select_family on public.tasks;
create policy tasks_select_family on public.tasks
for select to authenticated
using (public.is_family_member(family_id));

drop policy if exists tasks_insert_family on public.tasks;
create policy tasks_insert_family on public.tasks
for insert to authenticated
with check (public.is_family_member(family_id) and created_by = auth.uid() and updated_by = auth.uid() and (completed_by is null or completed_by = auth.uid()));

drop policy if exists tasks_update_family on public.tasks;
create policy tasks_update_family on public.tasks
for update to authenticated
using (public.is_family_member(family_id))
with check (public.is_family_member(family_id) and updated_by = auth.uid() and (completed_by is null or completed_by = auth.uid()));

drop policy if exists tasks_delete_family on public.tasks;
create policy tasks_delete_family on public.tasks
for delete to authenticated
using (public.is_family_member(family_id));

-- Préférences : chaque utilisateur ne voit et ne modifie que les siennes.
drop policy if exists notification_preferences_self_select on public.notification_preferences;
create policy notification_preferences_self_select on public.notification_preferences
for select to authenticated using (user_id = auth.uid());

drop policy if exists notification_preferences_self_insert on public.notification_preferences;
create policy notification_preferences_self_insert on public.notification_preferences
for insert to authenticated
with check (user_id = auth.uid() and public.is_family_member(family_id));

drop policy if exists notification_preferences_self_update on public.notification_preferences;
create policy notification_preferences_self_update on public.notification_preferences
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid() and public.is_family_member(family_id));

drop policy if exists notification_preferences_self_delete on public.notification_preferences;
create policy notification_preferences_self_delete on public.notification_preferences
for delete to authenticated using (user_id = auth.uid());

-- Abonnements Push : chaque utilisateur ne gère que ses propres appareils.
drop policy if exists push_subscriptions_self_select on public.push_subscriptions;
create policy push_subscriptions_self_select on public.push_subscriptions
for select to authenticated using (user_id = auth.uid());

drop policy if exists push_subscriptions_self_insert on public.push_subscriptions;
create policy push_subscriptions_self_insert on public.push_subscriptions
for insert to authenticated
with check (user_id = auth.uid() and public.is_family_member(family_id));

drop policy if exists push_subscriptions_self_update on public.push_subscriptions;
create policy push_subscriptions_self_update on public.push_subscriptions
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid() and public.is_family_member(family_id));

drop policy if exists push_subscriptions_self_delete on public.push_subscriptions;
create policy push_subscriptions_self_delete on public.push_subscriptions
for delete to authenticated using (user_id = auth.uid());

-- Aucun accès client aux traces d’envoi.
revoke all on public.notification_deliveries from anon, authenticated;

grant select, insert, update, delete on public.tasks to authenticated;
grant select, insert, update, delete on public.notification_preferences to authenticated;
grant select, insert, update, delete on public.push_subscriptions to authenticated;

drop trigger if exists tasks_touch_updated_at on public.tasks;
create trigger tasks_touch_updated_at before update on public.tasks
for each row execute function public.touch_updated_at();

drop trigger if exists notification_preferences_touch_updated_at on public.notification_preferences;
create trigger notification_preferences_touch_updated_at before update on public.notification_preferences
for each row execute function public.touch_updated_at();

drop trigger if exists push_subscriptions_touch_updated_at on public.push_subscriptions;
create trigger push_subscriptions_touch_updated_at before update on public.push_subscriptions
for each row execute function public.touch_updated_at();

drop trigger if exists tasks_validate_member on public.tasks;
create trigger tasks_validate_member before insert or update on public.tasks
for each row execute function public.validate_task_member();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'tasks'
  ) then alter publication supabase_realtime add table public.tasks; end if;
end $$;

commit;
